name: ghosts
channels:
  - huggingface
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip
  - yapf=0.31
  - numpy=1.21
  - click=8.0
  - pillow=9.0
  - ninja=1.10
  - pytorch=1.11
  - cudatoolkit=11.3
  - tensorflow=2.4
  - transformers=4.14
  - pip:
      - aitextgen==0.5.2
